# This file defines the build process for Nixpacks.
# It should be in the root of your repository (e.g., c:\Users\TParis\Desktop\90IGISP\nixpacks.toml)

providers = ["node"] # Specify that this is a Node.js project

[phases.setup]
# Define Node.js and npm versions.
# Ensure these are compatible with your project.
# nodejs_18 should include npm. Removed explicit "npm" which caused the error.
nixPkgs = ["nodejs_18"]

[phases.install]
# Define the installation phase for dependencies.
commands = ["npm install"]

[phases.build]
# Define the build phase for the project.
commands = ["npm run build"]

[start]
# Define the start phase for the application.
commands = ["npm start"]