# This file defines the build process for Nixpacks.
# It should be in the root of your repository (e.g., c:\Users\TParis\Desktop\90IGISP\nixpacks.toml)

[phases.setup]
# Add "nodejs_18" and "npm" to the list of Nix packages.
# Ensure "npm" is included in the list.
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
# These commands run in the root of your repository.
# We cd into the application subdirectory '90IGISP' to run npm install.
cmds = [
  "echo 'INFO: Custom install phase started.'",
  "cd 90IGISP && npm install --no-cache --no-audit --no-fund --legacy-peer-deps --loglevel error --production=false",
  "echo 'INFO: Custom install phase completed.'"
]

[phases.build]
cmds = [
  "echo 'INFO: Custom build phase started (if applicable).'",
  # Example: if you had a build script in 90IGISP/package.json:
  # "cd 90IGISP && npm run build",
  "echo 'INFO: Custom build phase completed.'"
]

[start]
# This command defines how to start your application.
# It runs from the root of your repository.
cmd = "cd 90IGISP && node src/index.js"