[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install --no-audit --no-fund --production=false --loglevel=error --prefer-offline']

[phases.build]
cmds = ['cd 90IGISP && npm install --no-audit --no-fund --production=false --loglevel=error --prefer-offline']

[start]
cmd = "cd 90IGISP && node src/index.js"
