[build]
builder = "nixpacks"
# Tells Railway to look for nixpacks.toml in the project root for build instructions.
nixpacksConfigPath = "nixpacks.toml"

[deploy]
# The start command will be defined in nixpacks.toml's [start] phase.
# You can remove or comment out healthcheck settings if not immediately needed.
healthcheckPath = "/health" # Example, adjust if you have a health endpoint
healthcheckTimeout = 120
